# Generated by Django 3.1 on 2020-10-09 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', 'add_task_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='inserted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
