# Generated by Django 3.1.2 on 2020-10-08 16:27

import colorfield.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('inserted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
